#![cfg(test)]

use super::*;
use soroban_sdk::{symbol_short, testutils::Address as _, Address, Bytes, Env};

// Real UltraHonk artifacts from our kyc_proof circuit (Noir 1.0.0-beta.9 + bb
// v0.87.0), generated by circuits/scripts/build.sh. These exercise the actual
// on-chain BN254 verification path, not a stub.
const VK: &[u8] = include_bytes!("../../../fixtures/kyc/vk");
const PROOF: &[u8] = include_bytes!("../../../fixtures/kyc/proof");
const PUBLIC_INPUTS: &[u8] = include_bytes!("../../../fixtures/kyc/public_inputs");

fn setup(env: &Env) -> CredentialVerifierClient {
    let admin = Address::generate(env);
    let id = env.register(CredentialVerifier, (admin,));
    CredentialVerifierClient::new(env, &id)
}

#[test]
fn verifies_real_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let client = setup(&env);

    client.set_vk(&symbol_short!("kyc"), &Bytes::from_slice(&env, VK));
    let ok = client.verify_kyc_proof(
        &Bytes::from_slice(&env, PROOF),
        &Bytes::from_slice(&env, PUBLIC_INPUTS),
    );
    assert!(ok, "valid proof should verify");
}

#[test]
fn rejects_tampered_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let client = setup(&env);
    client.set_vk(&symbol_short!("kyc"), &Bytes::from_slice(&env, VK));

    // Flip a byte in the middle of the proof; same length, invalid content.
    let mut bad = PROOF.to_vec();
    bad[5000] ^= 0xff;
    let ok = client.verify_kyc_proof(
        &Bytes::from_slice(&env, &bad),
        &Bytes::from_slice(&env, PUBLIC_INPUTS),
    );
    assert!(!ok, "tampered proof must not verify");
}

#[test]
fn rejects_wrong_length_proof() {
    let env = Env::default();
    env.mock_all_auths();
    let client = setup(&env);
    client.set_vk(&symbol_short!("kyc"), &Bytes::from_slice(&env, VK));

    let ok = client.verify_kyc_proof(
        &Bytes::from_array(&env, &[0u8; 16]),
        &Bytes::from_slice(&env, PUBLIC_INPUTS),
    );
    assert!(!ok, "wrong-length proof must be rejected before verifying");
}

#[test]
#[should_panic]
fn set_vk_rejects_garbage() {
    let env = Env::default();
    env.mock_all_auths();
    let client = setup(&env);
    client.set_vk(&symbol_short!("kyc"), &Bytes::from_array(&env, &[1, 2, 3]));
}

#[test]
#[should_panic]
fn panics_without_vk() {
    let env = Env::default();
    env.mock_all_auths();
    let client = setup(&env);
    client.verify_age_proof(
        &Bytes::from_slice(&env, PROOF),
        &Bytes::from_slice(&env, PUBLIC_INPUTS),
    );
}
